### ISSUE TITLE
make keren data script error

### ISSUE THREAD

**Issue by ellispatrick** [SydneyBioX/SpatialDatasets#1]
The script needs revision.  It lacks

library(BiocParallel)
library(tidyr)
library(readr)
library(tibble)

and it fails at 

> patientData = patientData %>% 
+   rename(V1 = "patient",
+          V2 = "tumour_type") %>%
+   mutate(tumour_type = case_when(tumour_type == 0 ~ " ..." ... [TRUNCATED] 
Error in `rename()`:
! Can't rename columns that don't exist.
✖ Column `patient` doesn't exist.

More importantly -- is there any workflow associated with the Keren spe object?  I looked
at the tiff files and they are mostly black ... I applied to get the ionpath viewer access.  Am
I missing some documentation on what to do with this dataset?  I confess that I haven't read
the paper yet ...

Thanks

**Comment by fame2827** [comment]
fixed in last [commit](https://github.com/SydneyBioX/SpatialDatasets/commit/41c2abcbff55c08c2cd7f8f100cf978c86386166)
