### ISSUE TITLE
Dataset Not Found in ExperimentHub Error

### ISSUE THREAD

**Issue by DarioS** [SydneyBioX/SpatialDatasets#4]
It does seem to download completely, though.
```r
> library(SpatialDatasets)
> spe <- spe_Ali_2020()
|=============================================================================================================| 100%
snapshotDate(): 2024-04-29
Error in spe_Ali_2020() : "spe_Ali_2020" not found in ExperimentHub
```

**Comment by alexrunqin** [comment]
Could you put through your `sessionInfo()` and `BiocManager::version()` for when this doesn't work? Loading in the `spe_Ali_2020` dataset should work on SpatialDatasets >=1.4.0 and Bioconductor >=3.20

**Comment by DarioS** [comment]
It works today.
